package_update: true
packages:
- python3
- git
runcmd:
- echo "Environment setup complete."
write_files:
- content: 'Welcome to the VM for odissei-knowledge-graph

    Version: 1.0.1

    '
  path: /etc/motd
