#cloud-config
package_update: true
packages:
  - python3-pip
  - docker.io
write_files:
  - path: /etc/motd
    content: |
      Welcome to your RO-Crate provisioned VM!
runcmd:
  - systemctl start docker